apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: ${CLUSTER_NAME}
spec:
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: ${CLUSTER_NAME}
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: ${CLUSTER_NAME}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VCluster
metadata:
  name: ${CLUSTER_NAME}
spec:
  kubernetesVersion: "${KUBERNETES_VERSION}"
  helmRelease:
    values: "${HELM_VALUES:=}"
    chart: 
      name: vcluster
      repo: https://charts.loft.sh
      version: 0.11.1
  controlPlaneEndpoint:
    host: ${CLUSTER_NAME}.vclister.svc.local
    port: 443